### ISSUE TITLE
Make ToyData match other datasets

### ISSUE THREAD

**Issue by davidmascharka** [LLCogWorks2018/DataSets#7]
`ToyData` gets constructed, then is loaded using `load_data()`. None of the other datasets have this functionality. Should `ToyData`'s interface match everything else?

**Comment by rsokl** [comment]
Yes, this would be nice

**Comment by davidmascharka** [comment]
In light of our discussion in person about plotting, I think this should maybe be closed? Feel free to close if I'm right.
